USE linhtranne;

CREATE TABLE SP (
    MASP INT PRIMARY KEY,
    TENSP VARCHAR(255)
);

CREATE TABLE HOADON (
    MAHD INT PRIMARY KEY,
    TENHD VARCHAR(255)
);

CREATE TABLE CHITIETHOADON (
    MAHD INT,
    MASP INT,
    SOLUONG INT NOT NULL,
    PRIMARY KEY (MAHD, MASP),
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    FOREIGN KEY (MASP) REFERENCES SP(MASP)
);

SELECT 
    HOADON.MAHD,
    HOADON.TENHD,
    SP.MASP,
    SP.TENSP,
    CHITIETHOADON.SOLUONG
FROM 
    HOADON
JOIN 
    CHITIETHOADON ON HOADON.MAHD = CHITIETHOADON.MAHD
JOIN 
    SP ON CHITIETHOADON.MASP = SP.MASP;
