USE ss4;

CREATE TABLE ROOM(
CROOM_ID INT PRIMARY KEY AUTO_INCREMENT,
ROOMNAME VARCHAR(255) NOT NULL,
MANAGERNAME VARCHAR(255) NOT NULL
);	

CREATE TABLE COMPUTER(
COMPUTER_ID INT PRIMARY KEY AUTO_INCREMENT,
CROOM_ID INT NOT NULL,
SD VARCHAR(255) NOT NULL,
RAM INT NOT NULL,
CPUS VARCHAR(255) NOT NULL,
FOREIGN KEY (CROOM_ID) REFERENCES ROOM(CROOM_ID)
);

CREATE TABLE SUBJECTS(
SUBJECTS_ID INT PRIMARY KEY AUTO_INCREMENT,
CROOM_ID INT NOT NULL,
SUBJECT_NAME VARCHAR(255) NOT NULL,
SUBJECT_TIME DATETIME NOT NULL,
FOREIGN KEY (CROOM_ID) REFERENCES ROOM(CROOM_ID)
);

CREATE TABLE REGISTATION(
ROOM_ID INT NOT NULL,
SUBJECTS_ID INT NOT NULL,
REGISTATIONTIME DATE,
FOREIGN KEY (ROOM_ID) REFERENCES ROOM(CROOM_ID),
FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID)
);

