CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL CHECK (PRICE > 0),
    STOCK INT NOT NULL CHECK (STOCK >= 0),
    CATEGORY VARCHAR(100)
);

INSERT INTO PRODUCTS (NAME, PRICE, STOCK, CATEGORY)
VALUES
    ('IPHONE 14', 999.99, 20, 'ELECTRONICS'),
    ('SAMSUNG GALAXY S23', 849.99, 15, 'ELECTRONICS'),
    ('SONY HEADPHONES', 199.99, 30, 'ELECTRONICS'),
    ('WOODEN TABLE', 120.50, 10, 'FURNITURE'),
    ('OFFICE CHAIR', 89.99, 25, 'FURNITURE'),
    ('RUNNING SHOES', 49.99, 50, 'SPORTS'),
    ('BASKETBALL', 29.99, 100, 'SPORTS'),
    ('T-SHIRT', 19.99, 200, 'CLOTHING'),
    ('LAPTOP BAG', 39.99, 40, 'ACCESSORIES'),
    ('DESK LAMP', 25.00, 35, 'ELECTRONICS');

SELECT * FROM PRODUCTS 
WHERE CATEGORY = 'ELECTRONICS' 
AND PRICE > 200;
SELECT * FROM PRODUCTS 
WHERE STOCK < 20;
SELECT NAME, PRICE 
FROM PRODUCTS 
WHERE CATEGORY IN ('SPORTS', 'ACCESSORIES');
UPDATE PRODUCTS 
SET STOCK = 100 
WHERE NAME LIKE 'S%';
UPDATE PRODUCTS 
SET CATEGORY = 'PREMIUM ELECTRONICS' 
WHERE PRICE > 500;
DELETE FROM PRODUCTS 
WHERE STOCK = 0;
DELETE FROM PRODUCTS 
WHERE CATEGORY = 'CLOTHING' 
AND PRICE < 30;
