CREATE TABLE STUDENTS (
	STUDENT_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    STUDENT_NAME VARCHAR(255) NOT NULL,
    AGE INT NOT NULL CHECK(AGE > 0),
	EMAIL VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO STUDENTS (STUDENT_NAME, EMAIL, AGE) 
VALUES 
	('NGUYEN VAN A', 'NGUYENVANA@EXAMPLE.COM', 22), 
	('LE THI B', 'LETHIB@EXAMPLE.COM', 20), 
	('TRAN VAN C', 'TRANVANC@EXAMPLE.COM', 23), 
	('PHAM THI D', 'PHAMTHID@EXAMPLE.COM', 21);

DELETE FROM STUDENTS WHERE STUDENT_ID = 2;
