CREATE TABLE BOOKS (
	BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL 
);

INSERT INTO BOOKS (TITLE, PRICE, STOCK)
VALUES
	('TO KILL A MOCKINGBIRD', 120.00, 10),
	('1984', 90.00, 3),
	('THE GREAT GATSBY', 150.00, 20),
	('MOBY DICK', 200.00, 5),
	('PRIDE AND PREJUDICE', 50.00, 8);

SELECT * 
FROM BOOKS 
WHERE PRICE > 100;

DELETE FROM BOOKS
WHERE TITLE LIKE '%PRIDE%';
