CREATE TABLE KHACHHANG(
MAKH INT PRIMARY KEY,
TENKH VARCHAR(255) NOT NULL,
SODIENTHOAAI VARCHAR(255) NOT NULL
);

CREATE TABLE HOADON(
MAHD INT PRIMARY KEY,
NGAYLAP DATE NOT NULL,
MAKH INT,
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);