USE linhtranne;
USE linhtranne;

CREATE TABLE HOCSINH (
    maHS INT PRIMARY KEY NOT NULL,
    ten VARCHAR(20) NOT NULL
);
CREATE TABLE MON (
    MAMON INT PRIMARY KEY NOT NULL,
    TENMON VARCHAR(255) NOT NULL
);
CREATE TABLE DIEM (
    MAHS INT NOT NULL,
    MAMON INT NOT NULL,
    DIEM DECIMAL(10, 5) NOT NULL,
    PRIMARY KEY (MAHS, MAMON),
    FOREIGN KEY (MAHS) REFERENCES HOCSINH(MAHS),
    FOREIGN KEY (MAMON) REFERENCES MON(MAMON),
    CHECK (DIEM >= 0 AND DIEM <= 10)
);