CREATE TABLE SANPHAM(
	MASP INT PRIMARY KEY,
    TENSP VARCHAR(255),
	GIABAN DECIMAL(10,5),
    SOLUONG INT 
);
ALTER TABLE SanPham
MODIFY COLUMN TenSP VARCHAR(255) NOT NULL;

ALTER TABLE SanPham
MODIFY COLUMN GiaBan DECIMAL(10, 2) NOT NULL;
 
 